// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// rredisInternalCmd
SEXP rredisInternalCmd(RObject Rc, List Rargv);
RcppExport SEXP rredis_rredisInternalCmd(SEXP RcSEXP, SEXP RargvSEXP) {
BEGIN_RCPP
    SEXP __sexp_result;
    {
        Rcpp::RNGScope __rngScope;
        RObject Rc = Rcpp::as<RObject >(RcSEXP);
        List Rargv = Rcpp::as<List >(RargvSEXP);
        SEXP __result = rredisInternalCmd(Rc, Rargv);
        PROTECT(__sexp_result = Rcpp::wrap(__result));
    }
    UNPROTECT(1);
    return __sexp_result;
END_RCPP
}
