# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rredisInternalCmd <- function(Rc, Rargv) {
    .Call('rredis_rredisInternalCmd', PACKAGE = 'rredis', Rc, Rargv)
}

