# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rredisInternalAppendCmd <- function(Rc, Rargv) {
    .Call('rredis_rredisInternalAppendCmd', PACKAGE = 'rredis', Rc, Rargv)
}

rredisInternalCmd <- function(Rc, Rargv) {
    .Call('rredis_rredisInternalCmd', PACKAGE = 'rredis', Rc, Rargv)
}

rredisInternalResponse <- function(Rc) {
    .Call('rredis_rredisInternalResponse', PACKAGE = 'rredis', Rc)
}

